name: Continous Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        -uses: actions/checkout@v2

        -run: echo "Setting up NodeJs"
        -name: Setup NodeJS
         uses: actions/setup-node@v2-beta
         with:
          node-version: 12.x

        - name: GitHub Action for Yarn
           uses: Borales/actions-yarn@v2.1.0
             with:
             # Yarn command
              cmd: install # npm install/ yarn install
    
        - name: Creating build
          run: yarn build  

        -run: npm install -g surge
        -run: echo "Deploying Website"
        -run: surge ./ ${{ secrets.SURGE_DOMAIN }}  --token ${{ secrets.SURGE_TOKEN }}

        -run: echo Please visit => ${{ secrets.SURGE_DOMAIN }}